//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirTicket
    {
        public int Id { get; set; }
        public System.DateTime DateTimeIn { get; set; }
        public System.DateTime DateTimeOut { get; set; }
        public int Client { get; set; }
        public int Airport { get; set; }
    
        public virtual Airport Airport1 { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
