//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public int Client { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int Country { get; set; }
        public int Food { get; set; }
        public int Star { get; set; }
        public int NumberOfGuest { get; set; }
        public Nullable<int> NumberOfChild { get; set; }
        public int Status { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual TypeOfFood TypeOfFood { get; set; }
        public virtual StarOfHotel StarOfHotel { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
