//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int Id { get; set; }
        public int Hotel { get; set; }
        public int Kind { get; set; }
        public int Count { get; set; }
    
        public virtual Hotel Hotel1 { get; set; }
        public virtual KindOfRoom KindOfRoom { get; set; }
    }
}
