//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public decimal LName { get; set; }
        public string FName { get; set; }
        public string SName { get; set; }
        public string FNameEng { get; set; }
        public string SNameEng { get; set; }
        public string IntPassport { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Account { get; set; }
    }
}
